// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTemp = "temp"

// Temp mapped from table <temp>
type Temp struct {
	ID    int32    `gorm:"column:id;not null" json:"id"`
	Input string   `gorm:"column:input;not null" json:"input"`
	A     float64  `gorm:"column:A;not null" json:"A"`
	B     *float64 `gorm:"column:B" json:"B"`
	B0    *float64 `gorm:"column:B0" json:"B0"`
	B1    *float64 `gorm:"column:B1" json:"B1"`
	B2    *float64 `gorm:"column:B2" json:"B2"`
	B3    *float64 `gorm:"column:B3" json:"B3"`
	B4    *float64 `gorm:"column:B4" json:"B4"`
}

// TableName Temp's table name
func (*Temp) TableName() string {
	return TableNameTemp
}
